config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'static#landing_page'
  resources :users, only: [:show]
  resources :conversations
  resources :invitations, only: %i[new create]
  resources :chat_messages
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_message.rb
# frozen_string_literal: true

class ChatMessage < ApplicationRecord
  validates_presence_of :content
  belongs_to :user
  belongs_to :conversation
  enum state: %i[waiting sent]

  delegate :username, to: :user, prefix: false

  after_create_commit lambda {
    broadcast_prepend_to conversation,
                         partial: 'chat_messages/chat_message',
                         locals: { chat_message: self },
                         target: 'messages'
  }
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged finders]

  validates_presence_of :title
  validates_uniqueness_of :title

  belongs_to :moderator, class_name: 'User', foreign_key: 'user_id'
  has_many :invitations, dependent: :destroy
  has_many :users, through: :invitations
  has_many :chat_messages, dependent: :destroy

  delegate :username, to: :moderator, prefix: true
end

app/models/invitation.rb
# frozen_string_literal: true

class Invitation < ApplicationRecord
  belongs_to :conversation
  belongs_to :user, optional: true
  attr_accessor :user_lookup
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  extend FriendlyId
  friendly_id :username, use: :slugged

  validates_presence_of :username
  validates_uniqueness_of :username

  has_many :conversations

  has_many :invitations, dependent: :destroy
  has_many :invited_conversations, through: :invitations, source: :conversation
  has_many :chat_messages, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/chat_messages_controller.rb
# frozen_string_literal: true

class ChatMessagesController < ApplicationController
  def create
    @chat_message = ChatMessage.new(chat_message_params)
    respond_to do |format|
      if @chat_message.save
        format.turbo_stream
        format.html { redirect_to chat_message_path(@chat_message) }
      end
    end
  end

  private

  def chat_message_params
    params.require(:chat_message).permit(:content, :user_id, :conversation_id)
  end
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  before_action :authenticate_invite!, only: %i[show]

  def new
    @conversation = Conversation.new(user_id: current_user.id)
  end

  def create
    @conversation = Conversation.new(conversation_params)
    @conversation.save
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to conversation_path(@conversation) }
    end
  end

  def show
    @conversation = Conversation.friendly.find(params[:id])
    @messages = @conversation.chat_messages.reverse
  end

  def destroy
    @conversation = Conversation.friendly.find(params[:id])
    @conversation.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to user_path(current_user), notice: 'Conversation was successfully deleted.' }
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:title, :user_id)
  end

  def authenticate_invite!
    @conversation = Conversation.friendly.find(params[:id])
    return if @conversation.moderator == current_user
    return if @conversation.users.include?(current_user)

    redirect_to root_path, notice: 'You are not invited to this conversation'
  end
end

app/controllers/invitations_controller.rb
# frozen_string_literal: true

class InvitationsController < ApplicationController
  def new
    @conversation = Conversation.friendly.find(params[:conversation_id])
    @invitation = Invitation.new(conversation_id: @conversation.id)
  end

  def create
    @invitation = Invitation.new(invitation_params)
    user = find_user(@invitation.user_lookup)

    if user
      @invitation.user_id = user.id
      @invitation.save
    else
      render turbo_stream: turbo_stream.replace('flash', partial: 'layouts/flash', locals: { notice: 'User Not Found' })
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:conversation_id, :user_lookup)
  end

  def find_user(query)
    User.find_by(email: query) || User.find_by(username: query)
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  skip_before_action :authenticate_user!

  def landing_page
    return unless user_signed_in?

    redirect_to user_path(current_user)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
    @conversations = @user.conversations.order(updated_at: :desc) + @user.invited_conversations
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/views/chat_messages/_chat_message.html.erb
<%= render ChatMessageComponent.new(chat_message: chat_message) %>

app/views/chat_messages/_form.html.erb
<%= turbo_frame_tag "message_form" do %>
  <%= simple_form_for chat_message, data: { controller: "reset", action: "turbo:submit-end->reset#clear" } do |f| %>
    <div class='flex w-full items-end w-full shadow-xl border rounded-lg'>
      <%= f.input :user_id, as: :hidden  %>
      <%= f.input :conversation_id, as: :hidden %>
      <%= f.input :content, label: false, as: :string, wrapper_html: { class: 'w-full grow' }, input_html: { class: 'grow h-10 rounded-r-none rounded-l-lg' } %>
      <%= f.submit '📩', id: 'submit-chat-message', class: 'px-4 bg-gray-800 rounded-r-lg h-10' %>
    </div>
  <% end %>
<% end %>

app/views/conversations/_form.html.erb
<%= simple_form_for conversation do |f| %>
  <div class='grid gap-4'>
    <%= f.input :user_id, as: :hidden %>
    <%= f.input :title %>
    <%= f.submit class: 'bg-gray-800 rounded p-2 text-white w-min ' %>
  </div>
<% end %>

app/views/conversations/create.turbo_stream.erb
<%= turbo_stream.prepend "conversations" do %>
  <%= render ConversationComponent.new(conversation: @conversation) %>
<% end %>

app/views/conversations/destroy.turbo_stream.erb
<%= turbo_stream.remove(@conversation) %>

app/views/conversations/new.html.erb
<%= render ModalComponent.new(title: "Start a Conversation") do %>
  <%= render "form", conversation: @conversation %>
<% end %>

app/views/conversations/show.html.erb
<%= turbo_stream_from @conversation %>
<div class="flex flex-col gap-4 h-[75vh]">
  <div class='flex gap-4 justify-between items-center'>
    <h1 class='text-4xl font-bold'><%= @conversation.title %></h1>
    <div class='flex gap-4 w-full flex-row-reverse'>
      <% if current_user == @conversation.moderator %>

        <%= button_to conversation_path(@conversation),
                      id: 'delete_link',
                      method: :delete,
                      class: "p-2",
                      data: {
                        turbo: false,
                        confirm: 'Are you sure you want to delete this conversation?'
                      } do %>
          ❌
        <% end %>
      <% end %>

      <%= link_to 'Invite Users',
                  new_invitation_path(conversation_id: @conversation.id),
                  class: "bg-gray-800 text-white rounded p-2",
                  data: { turbo_frame: 'modal' } %>
    </div>
  </div>
  <%= turbo_frame_tag 'messages', class:'bg-white border rounded p-4 shadow-xl h-full overflow-y-scroll flex flex-col-reverse gap-4 row-span-3' do %>
    <%= render(ChatMessageComponent.with_collection(@messages)) %>
  <% end %>
  <%= render partial: 'chat_messages/form', locals: {chat_message: ChatMessage.new(user_id: current_user.id, conversation_id: @conversation.id) } %>
</div>

app/views/invitations/_form.html.erb
<div id='invitation-form'>
<%= simple_form_for invitation do |f| %>
  <div class='grid gap-4'>
    <%= f.input :user_lookup, label: 'Username or Email' %>
    <%= f.input :conversation_id, as: :hidden %>

    <%= f.submit class: 'bg-gray-800 rounded p-2 text-white w-min ' %>
  </div>
<% end %>
</div>

app/views/invitations/new.html.erb
<%= render ModalComponent.new(title: "Invites") do %>
  <% unless @conversation.users.present? %>
    No users in this conversation
  <% end %>
  <div class='flex gap-2'>
    <% @conversation.users.each do |user| %>
      ⬤
      <b><%= user.username %></b>
      <i><%= user.email %></i>
    <% end %>
  </div>
  <hr>
  <h2 class='font-bold text-lg'>Invite another user</h2>
  <%= render "form", invitation: @invitation %>
<% end %>

app/views/layouts/_flash.html.erb
<%= turbo_frame_tag "flash" do %>
  <% flash.each do |flash_type, message| %>
    <div class="w-full bg-red-200 text-center">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_logo.html.erb
<% size ||= :md %>
<% classes = 'text-8xl rounded-xl px-6 py-4' if size == :xl %>
<% classes = 'text-4xl rounded-xl px-4 py-3' if size == :lg %>
<% classes = 'text-lg rounded-lg px-4 py-3' if size == :md %>
<% classes = 'rounded px-3 py-2' if size == :sm %>
<% classes = 'text-sm rounded px-2 py-1' if size == :xs %>

<% color ||= :black %>
<% classes += ' bg-black text-white' if color == :black %>
<% classes += ' bg-white text-black' if color == :white %>
<% classes += ' bg-red-700 text-white' if color == :red %>
<div class="font-black tracking-tighter w-min <%= classes %>">
  R◉UNDTABLE
</div>

app/views/layouts/_nav.html.erb
<div class='bg-black text-white flex gap-4 justify-between p-2'>
  <%= link_to :root do %>
    <%= render 'layouts/logo', size: :xs %>
  <% end %>
  <div class='flex gap-4'>
    <% if current_user %>
      Hello, <%= link_to current_user.username, user_path(current_user) %>
      <%= button_to 'Log Out', destroy_user_session_path, method: :delete, data: { turbo: false } %>
    <% else %>
      <%= link_to 'Log In', new_user_session_path, class: 'mr-4' %>
      <%= link_to 'Sign Up', new_user_registration_path %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roundtable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class='bg-gray-200'>
    <%= turbo_frame_tag "modal" %>
    <%= render 'layouts/flash' %>
    <%= render 'layouts/nav' %>
    <div class='container mx-auto mt-16 grid gap-4 min-h-full'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<h1 class='font-bold text-2xl'><%= @user.username %></h1>
<div class='grid gap-4 border rounded-xl shadow-xl p-8 bg-white'>
  <div class='flex justify-between w-full'>
    <h1 class='font-bold text-xl'>My Conversations</h1>

      <%= link_to new_conversation_path,
                  class: "bg-gray-800 text-white rounded p-2 w-fit text-xs",
                  data: { turbo_frame: 'modal' } do %>
          <div class='break-keep w-full'>New Conversation</div>
      <% end %>

  </div>
  <%= turbo_frame_tag 'conversations', class:'grid md:grid-cols-3 xl:grid-cols-4 gap-4' do %>
    <% if @user.conversations %>
      <%= render(ConversationComponent.with_collection(@conversations)) %>
    <% else %>
      No Conversations
    <% end %>
  <% end %>
</div>